global.Web3 = require("web3")
global.HDWalletProvider = require("@truffle/hdwallet-provider")
global.bip39 = require('bip39')
global.sjcl = require("sjcl")
require("sjcl/core/ctr")
require("sjcl/core/codecBytes")